package com.mbridge.msdk.widget.custom.a;

/* compiled from: ParamValue.java */
/* loaded from: E:\TSN-r\205dec\6400276.dex */
public enum c {
    id,
    layout_width,
    layout_height,
    orientation,
    layout_centerHorizontal,
    layout_centerVertical,
    layout_below,
    layout_above,
    layout_toRightOf,
    layout_toLeftOf,
    layout_marginLeft,
    layout_marginRight,
    layout_marginTop,
    layout_marginBottom,
    layout_bottom,
    layout_margin,
    layout_gravity,
    layout_alignParentRight,
    layout_alignParentLeft,
    layout_alignParentBottom,
    layout_alignParentTop,
    layout_weight,
    divider,
    splitMotionEvents,
    cacheColorHint,
    verticalSpacing,
    horizontalSpacing,
    text,
    ellipsize,
    fadingEdge,
    scrollHorizontally,
    textColor,
    textSize,
    singleLine,
    visibility,
    background,
    textStyle,
    style,
    src,
    gravity,
    numColumns,
    contentDescription,
    scaleType,
    paddingBottom,
    paddingTop,
    letterSpacing,
    paddingRight,
    layout_right
}
