package com.kwad.sdk.core.p389b.p390a;

import com.ksad.annotation.invoker.ForInvoker;
import com.kwad.sdk.commercial.model.HybridLoadMsg;
import com.kwad.sdk.commercial.model.SDKInitMsg;
import com.kwad.sdk.commercial.model.WebCloseStatus;
import com.kwad.sdk.commercial.model.WebViewCommercialMsg;
import com.kwad.sdk.commercial.model.WebViewLoadMsg;
import com.kwad.sdk.commercial.p372a.C9814b;
import com.kwad.sdk.commercial.p373b.C9820b;
import com.kwad.sdk.commercial.p374c.AbstractC9822a;
import com.kwad.sdk.commercial.p375d.C9827b;
import com.kwad.sdk.commercial.p376e.C9831b;
import com.kwad.sdk.commercial.p376e.C9832c;
import com.kwad.sdk.commercial.p377f.C9834b;
import com.kwad.sdk.commercial.p378g.C9836b;
import com.kwad.sdk.commercial.p380i.C9843b;
import com.kwad.sdk.commercial.p381j.C9844a;
import com.kwad.sdk.commercial.p381j.C9847b;
import com.kwad.sdk.core.InterfaceC10273d;
import com.kwad.sdk.core.imageloader.ImageLoaderInfo;
import com.kwad.sdk.core.network.C10424i;
import com.kwad.sdk.core.network.C10434j;
import com.kwad.sdk.core.report.C10460j;
import com.kwad.sdk.core.request.model.C10475b;
import com.kwad.sdk.core.request.model.C10478d;
import com.kwad.sdk.core.request.model.C10480f;
import com.kwad.sdk.core.request.model.C10481g;
import com.kwad.sdk.core.request.model.StatusInfo;
import com.kwad.sdk.core.response.model.ABParams;
import com.kwad.sdk.core.response.model.AdGlobalConfigInfo;
import com.kwad.sdk.core.response.model.AdInfo;
import com.kwad.sdk.core.response.model.AdMatrixInfo;
import com.kwad.sdk.core.response.model.AdProductInfo;
import com.kwad.sdk.core.response.model.AdStatusInfo;
import com.kwad.sdk.core.response.model.AdStyleInfo;
import com.kwad.sdk.core.response.model.AdTemplate;
import com.kwad.sdk.core.response.model.AdVideoPreCacheConfig;
import com.kwad.sdk.core.response.model.CouponInfo;
import com.kwad.sdk.core.response.model.FeedSlideConf;
import com.kwad.sdk.core.response.model.HttpDnsInfo;
import com.kwad.sdk.core.response.model.PageInfo;
import com.kwad.sdk.core.response.model.PhotoInfo;
import com.kwad.sdk.core.response.model.TKAdLiveShopItemInfo;
import com.kwad.sdk.core.response.model.TemplateConfig;
import com.kwad.sdk.core.response.model.VideoPlayerStatus;
import com.kwad.sdk.core.response.p408a.C10482a;
import com.kwad.sdk.core.scene.URLPackage;
import com.kwad.sdk.core.threads.C10511b;
import com.kwad.sdk.core.threads.C10515d;
import com.kwad.sdk.internal.api.AdLabelImpl;
import com.kwad.sdk.internal.api.NativeAdExtraDataImpl;
import com.kwad.sdk.internal.api.SceneImpl;
import com.kwad.sdk.internal.api.SplashExtraDataImpl;
import com.kwad.sdk.p435h.p436a.C10771a;
import com.kwad.sdk.p435h.p436a.C10772b;
import com.kwad.sdk.p445n.C10882k;
import com.kwad.sdk.utils.p451b.C11038a;
import java.util.HashMap;
import java.util.Map;

/* renamed from: com.kwad.sdk.core.b.a.ft */
/* loaded from: E:\fuckcool\tsn\7241516.dex */
public final class C10070ft {
    public static Map<Class<? extends C10482a>, InterfaceC10273d> ava;

    static {
        HashMap hashMap = new HashMap();
        ava = hashMap;
        hashMap.put(AdMatrixInfo.MerchantLiveReservationInfo.LiveReservationPlayEndInfo.class, new C10078ga());
        ava.put(AdInfo.UnDownloadConf.class, new C10193kh());
        ava.put(HttpDnsInfo.class, new C10046ew());
        ava.put(AdMatrixInfo.Styles.class, new C10178jt());
        ava.put(URLPackage.class, new C10192kg());
        ava.put(NativeAdExtraDataImpl.class, new C10092go());
        ava.put(AdInfo.AdSplashInfo.class, new C9929an());
        ava.put(AdMatrixInfo.MatrixTemplate.class, new C10087gj());
        ava.put(AdInfo.H5Config.class, new C10039ep());
        ava.put(AdStyleInfo.PlayDetailInfo.PatchAdInfo.class, new C10115hk());
        ava.put(AdStyleInfo.PlayEndInfo.EndTopToolBarInfo.class, new C10007dk());
        ava.put(ImageLoaderInfo.class, new C10051fa());
        ava.put(AdInfo.NativeAdInfo.class, new C10093gp());
        ava.put(AdMatrixInfo.RewardVideoInteractInfo.class, new C10137if());
        ava.put(AdInfo.AdBaseInfo.class, new C10131i());
        ava.put(AdMatrixInfo.TemplateData.class, new C10186ka());
        ava.put(TemplateConfig.class, new C10183jy());
        ava.put(AdMatrixInfo.FullScreenInfo.class, new C10028ee());
        ava.put(AdStyleInfo.PlayDetailInfo.DetailTopToolBarInfo.class, new C9994cy());
        ava.put(C10771a.class, new C10109he());
        ava.put(AdMatrixInfo.RewardWebTaskCloseInfo.class, new C10139ih());
        ava.put(AdInfo.class, new C10224v());
        ava.put(AdStatusInfo.class, new C9930ao());
        ava.put(C10772b.class, new C10110hf());
        ava.put(C10480f.class, new C10181jw());
        ava.put(C10515d.class, new C10188kc());
        ava.put(AdStyleInfo.PlayEndInfo.AdWebCardInfo.class, new C9938aw());
        ava.put(AdStyleInfo.PlayDetailInfo.class, new C10118hn());
        ava.put(AdStyleInfo.PlayDetailInfo.DrawAdInfo.class, new C10003dg());
        ava.put(AdGlobalConfigInfo.class, new C10222t());
        ava.put(AdStyleInfo.class, new C9932aq());
        ava.put(FeedSlideConf.class, new C10019dw());
        ava.put(StatusInfo.SplashStyleControl.class, new C10169jk());
        ava.put(C9820b.class, new C9949bg());
        ava.put(AdInfo.AdMaterialInfo.MaterialFeature.class, new C10083gf());
        ava.put(C9814b.class, new C9945bc());
        ava.put(C10481g.class, new C10198km());
        ava.put(AdStyleInfo.PlayDetailInfo.DetailCommonInfo.class, new C9993cx());
        ava.put(AdInfo.FullScreenVideoInfo.class, new C10029ef());
        ava.put(C11038a.class, new C10074fx());
        ava.put(AdProductInfo.class, new C9926ak());
        ava.put(AdTemplate.class, new C9933ar());
        ava.put(ABParams.class, new C9915a());
        ava.put(WebViewCommercialMsg.class, new C10210ky());
        ava.put(AdMatrixInfo.ActionBarInfoNew.class, new C9996d());
        ava.put(AdMatrixInfo.ActivityMiddlePageInfo.class, new C10077g());
        ava.put(AdInfo.AdAggregateInfo.class, new C10104h());
        ava.put(AdInfo.AdFeedInfo.class, new C10220r());
        ava.put(AdMatrixInfo.SplashInfo.class, new C10161jc());
        ava.put(AdMatrixInfo.BottomBannerInfo.class, new C9963bu());
        ava.put(AdInfo.CallBackStrategyInfo.class, new C9965bw());
        ava.put(CouponInfo.class, new C9985cp());
        ava.put(WebCloseStatus.class, new C10209kx());
        ava.put(AdInfo.PlayableStyleInfo.class, new C10124ht());
        ava.put(AdStyleInfo.AdBrowseInfo.class, new C10185k());
        ava.put(PhotoInfo.BaseInfo.class, new C9957bo());
        ava.put(AdMatrixInfo.FeedInfo.class, new C10017du());
        ava.put(C9827b.class, new C10215m());
        ava.put(C10882k.C10885a.C10886a.class, new C10171jm());
        ava.put(AdInfo.AdRewardInfo.class, new C9927al());
        ava.put(AdInfo.ComplianceInfo.class, new C9975cf());
        ava.put(AdInfo.DownloadSafeInfo.class, new C10000dd());
        ava.put(AdMatrixInfo.BaseMatrixTemplate.class, new C9959bq());
        ava.put(C10511b.class, new C10187kb());
        ava.put(StatusInfo.NativeAdStyleControl.class, new C10096gs());
        ava.put(C10478d.class, new C10101gx());
        ava.put(AdInfo.SmallAppJumpInfo.class, new C10153iv());
        ava.put(AdMatrixInfo.CycleAggregateInfo.class, new C9989ct());
        ava.put(StatusInfo.class, new C10175jq());
        ava.put(AbstractC9822a.class, new C9958bp());
        ava.put(AdStyleInfo.PlayDetailInfo.DetailWebCardInfo.class, new C9995cz());
        ava.put(StatusInfo.SplashAdInfo.class, new C10157iz());
        ava.put(C9836b.class, new C10042es());
        ava.put(C9831b.class, new C10217o());
        ava.put(C10434j.class, new C10103gz());
        ava.put(AdInfo.AdTrackInfo.class, new C9934as());
        ava.put(AdInfo.CutRuleInfo.class, new C9988cs());
        ava.put(AdMatrixInfo.InstalledActivateInfo.class, new C10058fh());
        ava.put(C9847b.class, new C9936au());
        ava.put(AdInfo.AdvertiserInfo.class, new C9939ax());
        ava.put(PageInfo.class, new C10112hh());
        ava.put(C10882k.C10885a.class, new C10214lb());
        ava.put(AdStyleInfo.ExtraDisplayInfo.class, new C10013dq());
        ava.put(AdMatrixInfo.MatrixTag.class, new C10086gi());
        ava.put(AdInfo.MaterialSize.class, new C10085gh());
        ava.put(AdInfo.AdConversionInfo.DeeplinkItemInfo.class, new C9991cv());
        ava.put(AdVideoPreCacheConfig.class, new C9937av());
        ava.put(AdMatrixInfo.AggregationCardInfo.class, new C9940ay());
        ava.put(AdMatrixInfo.DownloadTexts.class, new C10002df());
        ava.put(SceneImpl.class, new C10146io());
        ava.put(TKAdLiveShopItemInfo.class, new C10179ju());
        ava.put(AdMatrixInfo.ShakeInfo.class, new C10147ip());
        ava.put(AdMatrixInfo.RewardVideoTaskInfo.class, new C10138ig());
        ava.put(AdMatrixInfo.AdInteractionInfo.class, new C10226x());
        ava.put(AdInfo.AdInsertScreenInfo.class, new C10225w());
        ava.put(StatusInfo.NativeAdRequestInfo.class, new C10094gq());
        ava.put(SplashExtraDataImpl.class, new C10160jb());
        ava.put(AdStyleInfo.ExposeTagInfo.class, new C10011do());
        ava.put(C9843b.class, new C10154iw());
        ava.put(AdStyleInfo.PlayEndInfo.class, new C10120hp());
        ava.put(HybridLoadMsg.class, new C10047ex());
        ava.put(PhotoInfo.class, new C10117hm());
        ava.put(C10460j.class, new C10008dl());
        ava.put(AdLabelImpl.class, new C10227y());
        ava.put(AdMatrixInfo.StyleInfo.class, new C10177js());
        ava.put(AdInfo.AdStyleConfInfo.class, new C9931ap());
        ava.put(C9844a.C9846a.class, new C10191kf());
        ava.put(AdInfo.AdConversionInfo.class, new C10212l());
        ava.put(AdInfo.UnDownloadRegionConf.class, new C10194ki());
        ava.put(AdStyleInfo.FeedAdInfo.class, new C10015ds());
        ava.put(WebViewLoadMsg.class, new C10211kz());
        ava.put(AdProductInfo.SpikeInfo.class, new C10155ix());
        ava.put(AdMatrixInfo.PreLandingPageTKInfo.class, new C10126hv());
        ava.put(AdMatrixInfo.RotateDegreeInfo.class, new C10141ij());
        ava.put(AdMatrixInfo.SplashEndCardTKInfo.class, new C10159ja());
        ava.put(C9832c.class, new C10218p());
        ava.put(C10475b.class, new C9997da());
        ava.put(HttpDnsInfo.IpInfo.class, new C10065fo());
        ava.put(PhotoInfo.VideoInfo.class, new C10200ko());
        ava.put(AdStyleInfo.PlayDetailInfo.PatchEcInfo.class, new C10116hl());
        ava.put(AdMatrixInfo.AdDataV2.class, new C10219q());
        ava.put(SDKInitMsg.class, new C10143il());
        ava.put(AdInfo.AdShowVideoH5Info.class, new C9928am());
        ava.put(AdMatrixInfo.SplashActionBarInfo.class, new C10156iy());
        ava.put(AdMatrixInfo.SplashSlideInfo.class, new C10168jj());
        ava.put(AdMatrixInfo.EndCardInfo.class, new C10006dj());
        ava.put(AdMatrixInfo.NeoVideoInfo.class, new C10100gw());
        ava.put(AdMatrixInfo.RotateInfo.class, new C10142ik());
        ava.put(AdInfo.NativeAdShakeInfo.class, new C10095gr());
        ava.put(AdStyleInfo.PlayDetailInfo.ActionBarInfo.class, new C9969c());
        ava.put(AdMatrixInfo.InterstitialCardInfo.class, new C10061fk());
        ava.put(AdGlobalConfigInfo.NeoScanAggregationSceneInfo.class, new C10098gu());
        ava.put(C9834b.class, new C9992cw());
        ava.put(AdMatrixInfo.SplashPlayCardTKInfo.class, new C10164jf());
        ava.put(AdMatrixInfo.MerchantLiveReservationInfo.class, new C10088gk());
        ava.put(VideoPlayerStatus.class, new C10204ks());
        ava.put(AdStyleInfo.PlayDetailInfo.WidgetAdInfo.class, new C10213la());
        ava.put(AdInfo.AdPreloadInfo.class, new C9925aj());
        ava.put(C10424i.class, new C10102gy());
        ava.put(AdInfo.AdMaterialInfo.class, new C9922ag());
        ava.put(AdMatrixInfo.class, new C9923ah());
        m26947Dz();
    }

    /* renamed from: DA */
    public static Map<Class<? extends C10482a>, InterfaceC10273d> m26948DA() {
        return ava;
    }

    @ForInvoker(methodId = "registerHolder")
    /* renamed from: Dz */
    private static void m26947Dz() {
        C9976cg.m27122Dz();
        C9977ch.m27121Dz();
        C9978ci.m27120Dz();
        C9979cj.m27119Dz();
        C9980ck.m27118Dz();
        C9981cl.m27117Dz();
        C9982cm.m27116Dz();
        C9983cn.m27115Dz();
        C10021dy.m27040Dz();
        C10022dz.m27039Dz();
        C10024ea.m27036Dz();
        C10025eb.m27035Dz();
        C10026ec.m27034Dz();
        C10027ed.m27033Dz();
    }

    public static InterfaceC10273d getHolder(Class<? extends C10482a> cls) {
        return ava.get(cls);
    }
}
