package com.kwad.sdk.core.b.a;

import com.ksad.annotation.invoker.InvokeBy;
import com.kwad.components.core.video.a.d;
import com.kwad.components.core.webview.a.a;
import com.kwad.components.core.webview.jshandler.WebCardRegisterLiveMessageListener;
import com.kwad.components.core.webview.jshandler.WebCardRegisterLiveShopListener;
import com.kwad.components.core.webview.jshandler.WebCardVideoPositionHandler;
import com.kwad.components.core.webview.jshandler.a;
import com.kwad.components.core.webview.jshandler.ae;
import com.kwad.components.core.webview.jshandler.af;
import com.kwad.components.core.webview.jshandler.ah;
import com.kwad.components.core.webview.jshandler.ai;
import com.kwad.components.core.webview.jshandler.al;
import com.kwad.components.core.webview.jshandler.am;
import com.kwad.components.core.webview.jshandler.an;
import com.kwad.components.core.webview.jshandler.aq;
import com.kwad.components.core.webview.jshandler.ar;
import com.kwad.components.core.webview.jshandler.as;
import com.kwad.components.core.webview.jshandler.at;
import com.kwad.components.core.webview.jshandler.av;
import com.kwad.components.core.webview.jshandler.ax;
import com.kwad.components.core.webview.jshandler.ba;
import com.kwad.components.core.webview.jshandler.bb;
import com.kwad.components.core.webview.jshandler.bc;
import com.kwad.components.core.webview.jshandler.be;
import com.kwad.components.core.webview.jshandler.c;
import com.kwad.components.core.webview.jshandler.d;
import com.kwad.components.core.webview.jshandler.e;
import com.kwad.components.core.webview.jshandler.f;
import com.kwad.components.core.webview.jshandler.g;
import com.kwad.components.core.webview.jshandler.h;
import com.kwad.components.core.webview.jshandler.j;
import com.kwad.components.core.webview.jshandler.k;
import com.kwad.components.core.webview.jshandler.o;
import com.kwad.components.core.webview.jshandler.s;
import com.kwad.components.core.webview.jshandler.t;
import com.kwad.components.core.webview.jshandler.w;
import com.kwad.components.core.webview.tachikoma.a.h;
import com.kwad.components.core.webview.tachikoma.a.u;
import com.kwad.components.core.webview.tachikoma.a.x;
import com.kwad.sdk.j.a;
import com.kwad.sdk.j.b;
import com.kwad.sdk.kgeo.KGeoInfo;

/* JADX WARN: Classes with same name are omitted:
  E:\TSN-r\205dec\6241084.dex
 */
/* loaded from: E:\TSN-r\205dec\6520572.dex */
public final class cn {
    @InvokeBy(invokerClass = ft.class, methodId = "registerHolder")
    public static void Dz() {
        ft.DA().put(aq.a.class, new hi());
        ft.DA().put(ax.a.class, new gb());
        ft.DA().put(com.kwad.components.core.webview.a.c.class, new hd());
        ft.DA().put(bc.a.class, new et());
        ft.DA().put(com.kwad.components.core.webview.tachikoma.b.e.class, new bv());
        ft.DA().put(u.b.class, new jh());
        ft.DA().put(com.kwad.components.core.webview.tachikoma.b.l.class, new fz());
        ft.DA().put(at.a.class, new bm());
        ft.DA().put(an.b.class, new fq());
        ft.DA().put(as.a.class, new bd());
        ft.DA().put(com.kwad.components.core.webview.tachikoma.b.y.class, new ku());
        ft.DA().put(h.b.class, new hq());
        ft.DA().put(a.C0714a.class, new dh());
        ft.DA().put(WebCardVideoPositionHandler.VideoPosition.class, new kt());
        ft.DA().put(com.kwad.components.core.webview.tachikoma.b.r.class, new is());
        ft.DA().put(h.b.class, new em());
        ft.DA().put(ai.a.class, new ev());
        ft.DA().put(d.b.class, new kq());
        ft.DA().put(com.kwad.components.core.webview.tachikoma.b.x.class, new kr());
        ft.DA().put(com.kwad.components.core.n.c.d.class, new kj());
        ft.DA().put(KGeoInfo.class, new fu());
        ft.DA().put(com.kwad.components.core.webview.tachikoma.b.t.class, new iu());
        ft.DA().put(com.kwad.components.core.webview.tachikoma.b.n.class, new hc());
        ft.DA().put(com.kwad.components.core.webview.tachikoma.b.p.class, new ho());
        ft.DA().put(com.kwad.components.core.webview.tachikoma.b.a.class, new n());
        ft.DA().put(com.kwad.components.core.webview.tachikoma.b.i.class, new eo());
        ft.DA().put(a.C0651a.class, new db());
        ft.DA().put(a.b.class, new de());
        ft.DA().put(com.kwad.components.core.webview.tachikoma.b.v.class, new kk());
        ft.DA().put(d.a.class, new kp());
        ft.DA().put(an.a.class, new fp());
        ft.DA().put(com.kwad.components.core.webview.tachikoma.b.j.class, new fr());
        ft.DA().put(b.C0715b.class, new in());
        ft.DA().put(com.kwad.components.core.webview.tachikoma.b.s.class, new it());
        ft.DA().put(f.a.class, new ej());
        ft.DA().put(com.kwad.components.core.webview.tachikoma.b.w.class, new kn());
        ft.DA().put(a.C0652a.class, new ai());
        ft.DA().put(com.kwad.components.core.webview.tachikoma.b.b.class, new bf());
        ft.DA().put(a.c.class, new gt());
        ft.DA().put(o.a.class, new gl());
        ft.DA().put(af.a.class, new hs());
        ft.DA().put(e.a.class, new ei());
        ft.DA().put(s.a.class, new jr());
        ft.DA().put(av.a.class, new kw());
        ft.DA().put(WebCardRegisterLiveShopListener.AdLiveItemShopInfo.class, new z());
        ft.DA().put(k.b.class, new ff());
        ft.DA().put(as.b.class, new be());
        ft.DA().put(WebCardRegisterLiveMessageListener.AdLiveMessageInfoList.AdLiveMessageItemInfo.class, new ab());
        ft.DA().put(ba.a.class, new kv());
        ft.DA().put(com.kwad.components.core.webview.tachikoma.b.u.class, new jg());
        ft.DA().put(ah.a.class, new kl());
        ft.DA().put(x.a.class, new bh());
        ft.DA().put(com.kwad.components.core.webview.tachikoma.b.c.class, new bj());
        ft.DA().put(com.kwad.components.core.webview.tachikoma.b.m.class, new gn());
        ft.DA().put(ar.a.class, new ba());
        ft.DA().put(com.kwad.components.core.webview.tachikoma.b.g.class, new ce());
        ft.DA().put(com.kwad.components.core.webview.tachikoma.b.h.class, new cu());
        ft.DA().put(d.a.class, new eh());
        ft.DA().put(com.kwad.components.core.page.b.a.class, new fy());
        ft.DA().put(g.a.class, new ek());
        ft.DA().put(t.b.class, new jn());
        ft.DA().put(bb.a.class, new jx());
        ft.DA().put(al.a.class, new cq());
        ft.DA().put(com.kwad.components.core.webview.a.b.class, new hb());
        ft.DA().put(a.b.class, new di());
        ft.DA().put(com.kwad.components.core.webview.tachikoma.b.o.class, new hg());
        ft.DA().put(b.a.class, new im());
        ft.DA().put(be.a.class, new fs());
        ft.DA().put(com.kwad.components.core.webview.tachikoma.b.q.class, new iq());
        ft.DA().put(c.b.class, new ey());
        ft.DA().put(com.kwad.components.core.n.c.b.class, new ha());
        ft.DA().put(w.a.class, new u());
        ft.DA().put(WebCardVideoPositionHandler.VideoPosition.KSAdJSCornerModel.class, new fv());
        ft.DA().put(ae.a.class, new hr());
        ft.DA().put(WebCardRegisterLiveMessageListener.AdLiveMessageInfoList.class, new aa());
        ft.DA().put(j.a.class, new en());
        ft.DA().put(k.a.class, new fe());
        ft.DA().put(com.kwad.components.core.webview.tachikoma.b.f.class, new cb());
        ft.DA().put(com.kwad.sdk.a.a.a.a.class, new fg());
        ft.DA().put(am.b.class, new eq());
        ft.DA().put(h.a.class, new el());
        ft.DA().put(com.kwad.components.core.webview.tachikoma.b.d.class, new bl());
        ft.DA().put(com.kwad.components.core.k.a.class, new s());
    }
}
