package com.kwad.sdk.core.config;

import com.kwad.sdk.core.config.item.InstallActivateReminderConfigItem;
import com.kwad.sdk.core.config.item.TipsConfigItem;
import com.kwad.sdk.core.config.item.e;
import com.kwad.sdk.core.config.item.f;
import com.kwad.sdk.core.config.item.g;
import com.kwad.sdk.core.config.item.h;
import com.kwad.sdk.core.config.item.i;
import com.kwad.sdk.core.config.item.j;
import com.kwad.sdk.core.config.item.k;
import com.kwad.sdk.core.config.item.l;
import com.kwad.sdk.core.config.item.m;
import com.kwad.sdk.core.config.item.n;
import com.kwad.sdk.core.config.item.o;
import com.kwad.sdk.core.config.item.p;
import com.kwad.sdk.core.config.item.q;
import java.util.ArrayList;

/* JADX WARN: Classes with same name are omitted:
  E:\TSN-r\205dec\6241084.dex
 */
/* loaded from: E:\TSN-r\205dec\6520572.dex */
public final class c {
    public static k aqv = new k("batchReportCatchLimit", 20);
    public static k aqw = new k("exceptionCollectorSwitch", 1);
    public static k aqx = new k("catchExceptionReportSwitch", 1);
    public static k aqy = new k("mediaPlayerLogReport", 0);
    public static k aqz = new k("didCopySwitch", 1);
    public static k aqA = new k("enableHodor", 0);
    public static k aqB = new k("speedLimitSwitch", 1);
    public static k aqC = new k("speedLimitThreshold", 200);
    public static k aqD = new k("ksNativeAdCustomSwitch", 0);
    public static k aqE = new k("compoAndSoThreadPoolCoreSize", 0);
    public static k aqF = new k("forceActivateAfterInstalled", 0);
    public static k aqG = new k("spliceVideoInteractionType", 0);
    public static k aqH = new k("feedLoadOptimizeType", 0);
    public static k aqI = new k("feedLoadOptimizeExternalEnable", 0);
    public static k aqJ = new k("nativeAdSlideClickDisable", 0);
    public static k aqK = new k("interstitialAdLoadProcessChange", 0);
    public static k aqL = new k("interstitialAdActivityOpt", 0);
    public static k aqM = new k("formAdExitInterceptSwitch", 0);
    public static k aqN = new k("adLeaveConfirmSwitch", 0);
    public static k aqO = new k("viewLandingPageTaskDuration", 15);
    public static k aqP = new k("rewardAdVideoPreCacheSize", 800);
    public static com.kwad.sdk.core.config.item.d aqQ = new com.kwad.sdk.core.config.item.d("dataFlowAutoStartSwitch", false);
    public static m aqR = new m("deviceInfoDisableConfig", 0L);
    public static com.kwad.sdk.core.config.item.d aqS = new com.kwad.sdk.core.config.item.d("playerEnable", false);
    public static com.kwad.sdk.core.config.item.d aqT = new com.kwad.sdk.core.config.item.d("dynamicEnable", false);
    public static com.kwad.sdk.core.config.item.d aqU = new com.kwad.sdk.core.config.item.d("commercialLoggerDeviceSwitch", false);
    public static k aqV = new k("commercialLoggerSwitch", 1);
    public static p aqW = new p("tkSoUrlV7a", "");
    public static p aqX = new p("tkSoUrlV8a", "");
    public static com.kwad.sdk.core.config.item.d aqY = new com.kwad.sdk.core.config.item.d("useTKSoAll", false);
    public static l aqZ = new l("playerConfig", null);
    public static q ara = new q("pkgNameList", new ArrayList(0));
    public static q arb = new q("hostList", new ArrayList(0));
    public static q arc = new q("crashGatherRateConfigList", new ArrayList(0));
    public static TipsConfigItem ard = new TipsConfigItem();
    public static com.kwad.sdk.core.config.item.c are = new com.kwad.sdk.core.config.item.c();
    public static InstallActivateReminderConfigItem arf = new InstallActivateReminderConfigItem();
    public static e arg = new e();
    public static n arh = new n("realtimeReportActions", "");
    public static o ari = new o();
    public static k arj = new k("appInstallNoticeSecond", 0);
    public static k ark = new k("installFloatingLayerPostion", 0);
    public static k arl = new k("remindInstallStyle", 0);
    public static k arm = new k("remindInstallTime", 60);
    public static k arn = new k("watermarkKwaiIdSwitch", 0);
    public static k aro = new k("insertScreenV2Switch", 0);
    public static k arp = new k("insertScreenAutoPlaySwitch", 0);
    public static j arq = new j("insertScreenV2ShowConfig");
    public static k arr = new k("environmentDetectEnable", 0);
    public static k ars = new k("simCardInfoEnable", 0);
    public static k art = new k("baseStationEnable", 0);
    public static k aru = new k("sensorEventEnable2", 0);
    public static k arv = new k("lpAutoDownloadApkSwitch", 1);
    public static k arw = new k("autoDownloadUrlSwitch", 0);
    public static k arx = new k("insertScreenAdType", 0);
    public static k ary = new k("interstitialAutoCallAppCountDaily", 1);
    public static k arz = new k("mediaControlPlaySwitch", 1);
    public static p arA = new p("appStatusSoUrlV7a", "");
    public static p arB = new p("appStatusSoUrlV8a", "");
    public static p arC = new p("appStatusSoVersion", "");
    public static k arD = new k("deeplinkCheckSwitch", -3);
    public static com.kwad.sdk.core.config.item.d arE = new com.kwad.sdk.core.config.item.d("deeplinkWindowSwitch", false);
    public static h arF = new h();
    public static com.kwad.sdk.core.config.item.d arG = new com.kwad.sdk.core.config.item.d("adLiveSwitch", false);
    public static com.kwad.sdk.core.config.item.d arH = new com.kwad.sdk.core.config.item.d("TKSwitch", true);
    public static com.kwad.sdk.core.config.item.d arI = new com.kwad.sdk.core.config.item.d("llsidDisplaySwitch", true);
    public static com.kwad.sdk.core.config.item.d arJ = new com.kwad.sdk.core.config.item.d("reduceDeviceSigSwitch", true);
    public static com.kwad.sdk.core.config.item.d arK = new com.kwad.sdk.core.config.item.d("personalRecommend", false);
    public static k arL = new k("forceActivate", 0);
    public static k arM = new k("remindOpen", -1);
    public static com.kwad.sdk.core.config.item.d arN = new com.kwad.sdk.core.config.item.d("viewVisibleCheckLegacy", false);
    public static p arO = new p("nativeAndAnrDynamic", "");
    public static k arP = new k("kwaiAppVersionSwitch", 1);
    public static p arQ = new p("userAgent", com.kwad.sdk.core.network.p.getDefaultUserAgent());
    public static k arR = new k("biddingLogSwitch", 0);
    public static k arS = new k("forceActiveThreshold", 5);
    public static k arT = new k("forceActiveInterval", 3);
    public static k arU = new k("hybridEnable", 1);
    public static com.kwad.sdk.core.config.item.d arV = new com.kwad.sdk.core.config.item.d("wifiResumeDownload", false);
    public static g arW = new g("adExposureAreaPercent", 0.3f);
    public static g arX = new g("adExposureTime", -1.0f);
    public static g arY = new g("apmToRECommercialRatio", 0.0f);
    public static com.kwad.sdk.core.config.item.d arZ = new com.kwad.sdk.core.config.item.d("appInAdExposureBlacklist", false);
    public static com.kwad.sdk.core.config.item.d asa = new com.kwad.sdk.core.config.item.d("soDownloadBreakpointContinuation", true);
    public static k asb = new k("soLoadMaxRetryCount", 1);
    public static com.kwad.sdk.core.config.item.d asc = new com.kwad.sdk.core.config.item.d("feedAdForceGetAudioFocus", false);
    public static k asd = new k("feedAdWebviewOptimize", 1);
    public static com.kwad.sdk.core.config.item.d ase = new com.kwad.sdk.core.config.item.d("logCommandSwitch", false);
    public static com.kwad.sdk.core.config.item.d asf = new com.kwad.sdk.core.config.item.d("logRecordAllSwitch", false);
    public static m asg = new m("obiwanLogFilesDiskQuota", 52428800L);
    public static l ash = new l("logCommandResult", "", false);
    public static m asi = new m("validClickConvertTime", 1000L);
    public static com.kwad.sdk.core.config.item.d asj = new com.kwad.sdk.core.config.item.d("eplCommandSwitch", false);
    public static k ask = new k("playableAutoPlayEnable", 1);
    public static k asl = new k("netMonitorSwitch", 0);
    public static com.kwad.sdk.core.config.item.d asm = new com.kwad.sdk.core.config.item.d("ipDirectEnable", false);
    public static com.kwad.sdk.core.config.item.d asn = new com.kwad.sdk.core.config.item.d("ipPreferEnable", false);
    public static k aso = new k("weaponSwitch", 1);
    public static k asp = new k("kvModeV2", 0);
    public static i asq = new i();
    public static k asr = new k("idcRollbackInterval", 0);
    public static m ass = new m("currentServerTimeMs");
    public static k ast = new k("clientProofreadTimeErrorRangeHours", 100);
    public static g asu = new g("adTraceReportRate", 1.0f);
    public static k asv = new k("adTraceRepeatEnable", 0);
    public static k asw = new k("appHeartBeatInterval", 0);
    public static k asx = new k("adCacheCode", 0);
    public static p asy = new p("installTipsContentDesc", "");
    public static p asz = new p("installTipsPositiveActionDesc", "");
    public static p asA = new p("installTipsNegativeActionDesc", "");
    public static com.kwad.sdk.core.config.item.d asB = new com.kwad.sdk.core.config.item.d("threadOptEnable", false);
    public static p asC = new p("perfMonitorV2", "");
    public static k asD = new k("neoVideoAdaptStrategy", 1);
    public static k asE = new k("feedTKLoadTimeOut", 2500);
    public static com.kwad.sdk.core.config.item.d asF = new com.kwad.sdk.core.config.item.d("adCacheOptEnable", false);
    public static com.kwad.sdk.core.config.item.d asG = new com.kwad.sdk.core.config.item.d("autoShowActivityMiddlePage", false);
    public static k asH = new k("videoCacheOpt", 0);
    public static p asI = new p("ranger", "");
    public static p asJ = new p("eplV1", "");
    public static p asK = new p("threadPoolPerfMonitor", "");
    public static p asL = new p("threadPoolParams", "");
    public static f asM = new f("crashUploadRate", Double.valueOf(1.0d));
    public static f asN = new f("adFeedWidthMinPercent", Double.valueOf(0.3d));
    public static com.kwad.sdk.core.config.item.d asO = new com.kwad.sdk.core.config.item.d("videoPerfMonitor", false);
    public static com.kwad.sdk.core.config.item.d asP = new com.kwad.sdk.core.config.item.d("enableHookPluginResource", true);
    public static com.kwad.sdk.core.config.item.d asQ = new com.kwad.sdk.core.config.item.d("enableHookWrapperContext", true);
    public static com.kwad.sdk.core.config.item.d asR = new com.kwad.sdk.core.config.item.d("batchReportSkipJSONParseEnable", false);
    public static com.kwad.sdk.core.config.item.d asS = new com.kwad.sdk.core.config.item.d("enableAdTrackLog", true);
    public static com.kwad.sdk.core.config.item.d asT = new com.kwad.sdk.core.config.item.d("usePolicy64LevelDisable", false);
    public static com.kwad.sdk.core.config.item.d asU = new com.kwad.sdk.core.config.item.d("tkReportInfoSwitch", false);
    public static k asV = new k("tubeRenderType", 0);
    public static k asW = new k("useTKAdBrowse", 0);
    public static com.kwad.sdk.core.config.item.d asX = new com.kwad.sdk.core.config.item.d("enableMediaGetAdInfo", false);
    public static p asY = new p("trackBlackUrlConfig", "");
    public static k asZ = new k("tkMemCacheSize", 0);
    public static q ata = new q("preloadMemCacheTemplateIds", new ArrayList(0));
    public static k atb = new k("kGeoInfoConfig", 1);
    public static k atc = new k("appMonitorSwitch", 0);
    public static k atd = new k("videoCacheErrorCallbackSwitch", 0);
    public static k ate = new k("tkErrorDetailCount", 1);
    public static k atf = new k("videoLaunchOptimiseSwitch", 0);
    public static p atg = new p("localLogConfig", "");
    public static p ath = new p("adLogRetryConfig", "");

    public static void init() {
    }
}
