package t1;

import kotlin.Metadata;
import kotlin.NotImplementedError;
import kotlin.jvm.internal.f0;
import org.jetbrains.annotations.NotNull;

/* JADX WARN: Classes with same name are omitted:
  E:\TSN-r\205dec\5406560.dex
 */
/* compiled from: TestSdk.java */
/* loaded from: E:\TSN-r\205dec\6206960.dex */
public class a {

    /* compiled from: Parceler.kt */
    @Metadata(k = 3, mv = {1, 5, 1}, xi = 48)
    /* renamed from: t1.a$a  reason: collision with other inner class name */
    /* loaded from: E:\TSN-r\205dec\5406560.dex */
    public static final class C1330a {
        @NotNull
        public static <T> T[] a(@NotNull a<T> aVar, int i4) {
            f0.p(aVar, "this");
            throw new NotImplementedError("Generated by Android Extensions automatically");
        }
    }

    public static void a(String[] strArr) {
        q1.a.a().g("1", "wgydx", "42.49.134.163", "7788");
    }
}
