package com.mbridge.msdk.foundation.tools;

import com.baidu.mobads.sdk.api.IAdInterListener;
import com.kuaishou.weapon.p205p0.C7304t;
import com.mbridge.msdk.foundation.download.core.DownloadCommon;
import com.mbridge.msdk.foundation.entity.CampaignEx;
import com.mbridge.msdk.foundation.entity.CampaignUnit;
import com.umeng.analytics.pro.PathCenter;
import com.umeng.analytics.pro.UContent;
import com.umeng.analytics.pro.UMCommonContent;
import com.umeng.ccg.CcgConstant;
import com.umeng.socialize.net.dplus.CommonNetImpl;
import com.umeng.socialize.net.utils.SocializeProtocolConstants;
import java.util.HashMap;
import tv.danmaku.ijk.media.player.IjkMediaPlayer;

/* renamed from: com.mbridge.msdk.foundation.tools.p */
/* loaded from: E:\fuckcool\tsn\6520572.dex */
public final class MappingFile {

    /* renamed from: a */
    private static final HashMap<String, String> f31123a;

    static {
        HashMap<String, String> hashMap = new HashMap<>(280);
        f31123a = hashMap;
        hashMap.put("a", "读取电话状态");
        hashMap.put("b", "访问网络");
        hashMap.put("c", "允许应用程序请求安装包");
        hashMap.put("d", "访问网络状态");
        hashMap.put("e", "访问无线状态");
        hashMap.put("f", "读取外部存储");
        hashMap.put("g", "写入外部存储");
        hashMap.put("h", "唤醒锁定");
        hashMap.put("i", "获取任务信息");
        hashMap.put("j", "更改无线网络状态");
        hashMap.put("k", "变更网络状态");
        hashMap.put(C7304t.f25048d, "允许震动");
        hashMap.put("m", "访问粗略定位");
        hashMap.put("n", "访问精准定位");
        hashMap.put("o", "读取日志");
        hashMap.put("p", "开机自动运行");
        hashMap.put(CampaignEx.JSON_KEY_AD_Q, "排序系统任务");
        hashMap.put("r", "使用前台服务");
        hashMap.put("s", "挂载文件系统");
        hashMap.put(UMCommonContent.f37782aL, "允许忽略电池优化");
        hashMap.put("u", "获取应用大小");
        hashMap.put("v", "显示系统窗口");
        hashMap.put(IAdInterListener.AdReqParam.WIDTH, "写入设置");
        hashMap.put("x", "蓝牙");
        hashMap.put("y", "改变无线组播状态");
        hashMap.put(UMCommonContent.f37777aG, "访问定位额外命令");
        hashMap.put("aa", "摄像头");
        hashMap.put("ab", "获取账户");
        hashMap.put("ac", "读取联系人");
        hashMap.put(UMCommonContent.f37822az, "修改音频设置");
        hashMap.put("ae", "录制音频");
        hashMap.put("af", "蓝牙管理");
        hashMap.put("ag", "结束系统任务");
        hashMap.put("ah", "创建快捷方式");
        hashMap.put("ai", "验证账户");
        hashMap.put("aj", "设置桌面壁纸");
        hashMap.put(SocializeProtocolConstants.PROTOCOL_KEY_AK, "管理账户");
        hashMap.put(CampaignEx.JSON_KEY_AD_AL, "结束后台进程");
        hashMap.put(CommonNetImpl.f39529AM, "使用证书");
        hashMap.put("an", "写入同步设置");
        hashMap.put("ao", "禁用键盘锁");
        hashMap.put(IAdInterListener.AdReqParam.f8441AP, "使用闪光灯");
        hashMap.put("aq", "收集组件使用统计信息");
        hashMap.put("ar", "允许 NFC 通讯");
        hashMap.put(CommonNetImpl.f39530AS, "设置闹铃提醒");
        hashMap.put("at", "读取设置");
        hashMap.put("au", "移除快捷方式");
        hashMap.put("av", "允许应用使用指纹硬件");
        hashMap.put("aw", "读取日历");
        hashMap.put("ax", "写入日历");
        hashMap.put("ay", "读取用户的通话记录");
        hashMap.put("az", "读取同步状态");
        hashMap.put("ba", "电量统计");
        hashMap.put("bb", "拨打电话");
        hashMap.put("bc", "允许应用程序请求删除包");
        hashMap.put("bd", "连续广播");
        hashMap.put("be", "清除应用缓存");
        hashMap.put("bf", "变更配置");
        hashMap.put("bg", "读取收藏夹和历史记录");
        hashMap.put("bh", "状态栏控制");
        hashMap.put("bi", "管理对文档的访问");
        hashMap.put("bj", "使用设备支持的生物识别模式");
        hashMap.put("bk", "对希望访问通知政策的应用程序的标记权限");
        hashMap.put(PathCenter.f37701t, "注射事件");
        hashMap.put("bm", "读取同步设置");
        hashMap.put("bn", "设置调试程序");
        hashMap.put("bo", "管理账户");
        hashMap.put("bp", "绑定小插件");
        hashMap.put("bq", "允许应用程序访问用户用来测量身体内部情况的传感器数据，例如心率");
        hashMap.put("br", "改变组件状态");
        hashMap.put("bs", "清除用户数据");
        hashMap.put("bt", "删除应用");
        hashMap.put("bu", "电源管理");
        hashMap.put("bv", "请求安装软件包");
        hashMap.put("bw", "允许应用程序在Launcher中安装快捷方式");
        hashMap.put("bx", "永久 Activity");
        hashMap.put("by", "设置系统时间");
        hashMap.put("bz", "设置系统时区");
        hashMap.put("ca", "设置壁纸建议");
        hashMap.put("cb", "访问订阅内容");
        hashMap.put(CcgConstant.f38530a, "\t写入订阅内容");
        hashMap.put("cd", "允许使用设备的红外发射器（如果有）");
        hashMap.put("ce", "不再支持此权限");
        hashMap.put("cf", "屏幕定位");
        hashMap.put("cg", "使用 SIP 视频");
        hashMap.put("ch", "写入 GPRS 接入点设置");
        hashMap.put("ci", "写入收藏夹和历史记录");
        hashMap.put("cj", "允许呼叫应用继续在另一个应用中启动的呼叫");
        hashMap.put("ck", "访问登记属性");
        hashMap.put("cl", "获取模拟定位信息");
        hashMap.put(SocializeProtocolConstants.PROTOCOL_KEY_COMMENT_COUNT, "访问 Surface Flinger");
        hashMap.put("cn", "允许应用程序将语音邮件添加到系统中");
        hashMap.put("co", "允许该应用接听来电");
        hashMap.put("cp", "Android系统的可访问性服务");
        hashMap.put("cq", "允许程序内容被自动填写");
        hashMap.put("cr", "允许绑定到运营商应用程序中的服务的系统进程将有这个权限");
        hashMap.put("cs", "允许绑定到运营商应用程序中的服务的系统进程将具有此权限");
        hashMap.put("ct", "允许用户在一个应用里面直接分享内容到其他地方");
        hashMap.put("cu", "应用于CompanionDeviceService");
        hashMap.put("cv", "提供有关布尔状态的条件的服务");
        hashMap.put("cw", "绑定设备管理");
        hashMap.put("cx", "允许设备闲置、充电或锁屏时，可以显示特定的内容");
        hashMap.put("cy", "允许提供用于管理电话呼叫的用户界面");
        hashMap.put("cz", "绑定输入法");
        hashMap.put("da", "允许实现虚拟MIDI设备的服务");
        hashMap.put("db", "允许模拟Android服务组件内的NFC卡");
        hashMap.put(SocializeProtocolConstants.PROTOCOL_KEY_DESCRIPTOR, "允许接收在发布或删除新通知或其排名发生变化时来自系统的呼叫的服务");
        hashMap.put("dd", "允许实现打印服务");
        hashMap.put("de", "允许应用程序绑定到第三方快速设置磁贴");
        hashMap.put("df", "绑定 RemoteView");
        hashMap.put("dg", "允许来电过滤");
        hashMap.put("dh", "管理Android系统当前的通话，如来电显示，接听电话，挂断电话");
        hashMap.put("di", "允许创建拼写检查器类");
        hashMap.put("dj", "允许实现电视输入服务");
        hashMap.put(UMCommonContent.f37842bs, "实现处理OMTP或类似可视语音邮件的拨号程序服务");
        hashMap.put("dl", "全局语音交互服务");
        hashMap.put(C7304t.f25066v, "虚拟现实（VR）服务");
        hashMap.put("dn", "绑定壁纸");
        hashMap.put(CampaignUnit.JSON_KEY_DO, "允许运行v*n解决方案");
        hashMap.put(C7304t.f25061q, "允许应用程序在没有用户交互的情况下配对蓝牙设备");
        hashMap.put("dq", "必须能够发现附近的蓝牙设备并与之配对");
        hashMap.put(DownloadCommon.DOWNLOAD_REPORT_DOWNLOAD_RATE, "变成砖头");
        hashMap.put("ds", "应用删除时广播");
        hashMap.put(SocializeProtocolConstants.PROTOCOL_KEY_DT, "收到短信时广播");
        hashMap.put(UContent.f38113ac, "WAP PUSH 广播");
        hashMap.put("dv", "允许实现InCallServiceAPI的应用程序");
        hashMap.put("dw", "通话权限");
        hashMap.put("dx", "允许应用程序捕获音频输出");
        hashMap.put("dy", "手机优化大师扩展权限");
        hashMap.put("dz", "控制定位更新");
        hashMap.put("ea", "底层访问权限");
        hashMap.put("eb", "删除缓存文件");
        hashMap.put("ec", "应用诊断");
        hashMap.put("ed", "转存系统信息");
        hashMap.put("ee", "工厂测试模式");
        hashMap.put("ef", "强制后退");
        hashMap.put("eg", "获取账户");
        hashMap.put("eh", "允许应用程序获得屏幕锁定复杂性并提示用户将屏幕锁定更新到某个复杂程度");
        hashMap.put("ei", "允许全局搜索");
        hashMap.put("ej", "硬件测试");
        hashMap.put(SocializeProtocolConstants.PROTOCOL_KEY_ENTITY_KEY, "允许应用阻止在其顶部绘制非系统覆盖的窗口");
        hashMap.put(C7304t.f25058n, "允许应用访问采样率大于200Hz的传感器数据");
        hashMap.put("em", "安装定位提供");
        hashMap.put("en", "前台服务");
        hashMap.put("eo", "内部系统窗口");
        hashMap.put("ep", "允许应用程序在硬件中使用位置功能");
        hashMap.put("eq", "管理程序引用");
        hashMap.put("er", "允许应用程序修改和删除此设备或任何连接的存储设备上的媒体文件，而无需用户确认");
        hashMap.put("es", "允许查询正在进行的通话详细信息并管理正在进行的通话");
        hashMap.put("et", "允许通过自我管理的ConnectionServiceAPI管理自己的调用的调用应用程序");
        hashMap.put("eu", "软格式化");
        hashMap.put("ev", "允许应用程序知道正在播放的内容并控制其播放");
        hashMap.put("ew", "修改电话状态");
        hashMap.put("ex", "格式化文件系统");
        hashMap.put("ey", "社区权限");
        hashMap.put("ez", "高级权限");
        hashMap.put("fa", "允许应用程序接收NFC交易事件");
        hashMap.put("fb", "处理拨出电话");
        hashMap.put("fc", "屏幕截图");
        hashMap.put(IjkMediaPlayer.OnNativeInvokeListener.ARG_FD, "读取输入状态");
        hashMap.put("fe", "允许应用程序读取用户的共享音频集合");
        hashMap.put("ff", "允许应用程序读取用户的共享图像集合");
        hashMap.put("fg", "允许应用程序读取用户的共享视频集");
        hashMap.put("fh", "允许读取设备的电话号码");
        hashMap.put("fi", "读取短信内容");
        hashMap.put("fj", "允许应用程序读取系统中的语音邮件");
        hashMap.put("fk", "重启设备");
        hashMap.put("fl", "接收彩信");
        hashMap.put("fm", "接收短信");
        hashMap.put("fn", "接收 Wap Push");
        hashMap.put("fo", "允许应用通过CompanionDeviceManager请求将设备与“手表”关联");
        hashMap.put("fp", "允许随播应用在后台运行");
        hashMap.put("fq", "允许配套应用在后台使用数据");
        hashMap.put(SocializeProtocolConstants.PROTOCOL_KEY_FR, "允许应用程序（电话）向其他应用程序发送请求，以处理来电期间的响应消息操作");
        hashMap.put("fs", "发送短信");
        hashMap.put(SocializeProtocolConstants.PROTOCOL_KEY_FRIST_TIME, "设置 Activity 观察器");
        hashMap.put("fu", "允许应用程序广播Intent以为用户设置警报");
        hashMap.put("fv", "设置总是退出");
        hashMap.put("fw", "设置动画缩放");
        hashMap.put("fx", "设置屏幕方向");
        hashMap.put("fy", "设置应用参数");
        hashMap.put("fz", "设置进程限制");
        hashMap.put("ga", "发送永久进程信号");
        hashMap.put("gb", "允许财务应用读取过滤的短信息");
        hashMap.put("gc", "允许应用程序从后台启动前台服务，只能授予特权应用程序或具有SMS/EMERGENCY/SYSTEMGALLERY角色的应用程序");
        hashMap.put("gd", "状态栏控制");
        hashMap.put("ge", "更新设备状态");
        hashMap.put("gf", "允许读取设备标识符并使\u200b\u200b用基于ICC的身份验证，例如EAP-AKA");
        hashMap.put("gg", "允许应用程序写入（但不读取）用户的呼叫日志数据");
        hashMap.put("gh", "写入联系人");
        hashMap.put("gi", "写入 Google 地图数据");
        hashMap.put("gj", "读写系统敏感设置");
        hashMap.put("gk", "编写短信");
        hashMap.put("gl", "允许应用程序修改和删除系统中的现有语音邮件");
    }

    /* renamed from: a */
    public static String m21817a(String str) {
        HashMap<String, String> hashMap = f31123a;
        return (hashMap == null || !hashMap.containsKey(str)) ? "" : hashMap.get(str);
    }
}
