package com.tencent.connect.common;

import java.io.File;

/* JADX WARN: Classes with same name are omitted:
  E:\TSN-r\205dec\6206960.dex
 */
/* compiled from: ProGuard */
/* loaded from: E:\TSN-r\205dec\6400276.dex */
public class Constants {
    public static final int ACTIVITY_CANCEL = 0;
    public static final int ACTIVITY_OK = -1;
    public static final String APPID = "appid";
    public static final String APP_NAME = "app_name";
    public static String APP_SPECIFIC_ROOT = null;
    public static final String APP_VERSION_UNKNOWN = "UNKNOWN";
    public static final String CANCEL_URI = "auth://cancel";
    public static final String CLOSE_URI = "auth://close";
    public static final int CODE_REQUEST_MAX = 6656;
    public static final int CODE_REQUEST_MIN = 5656;
    public static final String DEFAULT_PF = "openmobile_android";
    public static final String DEFAULT_UIN = "1000";
    public static final String DOWNLOAD_URI = "download://";
    public static final String ENC_UTF_8 = "UTF-8";
    public static final int ERROR_CONNECTTIMEOUT = -7;
    public static final int ERROR_FILE_EXISTED = -11;
    public static final int ERROR_HTTPSTATUS_ERROR = -9;
    public static final int ERROR_IMAGE_TOO_LARGE = -16;
    public static final int ERROR_IO = -2;
    public static final int ERROR_JSON = -4;
    public static final int ERROR_LOCATION_TIMEOUT = -13;
    public static final int ERROR_LOCATION_VERIFY_FAILED = -14;
    public static final int ERROR_NETWORK_UNAVAILABLE = -10;
    public static final int ERROR_NO_AUTHORITY = -19;
    public static final int ERROR_NO_SDCARD = -12;
    public static final int ERROR_PARAM = -5;
    public static final int ERROR_PROXY_LOGIN_AND_QQ_VERSION_LOWER = -18;
    public static final int ERROR_QQVERSION_LOW = -15;
    public static final int ERROR_QQ_NOT_INSTALL = -20;
    public static final int ERROR_QQ_NOT_LOGIN = -21;
    public static final int ERROR_SOCKETTIMEOUT = -8;
    public static final int ERROR_UNKNOWN = -6;
    public static final int ERROR_URL = -3;
    public static final String FILE_PROVIDER_AUTHORITIES = "com.tencent.tauth.fileprovider";
    public static final boolean FLAG_DEBUG = true;
    public static final String FORCE_ACCOUNT_EQUAL = "force_account_equal";
    public static final String FOR_RESULT = "for_result";
    public static final String FROM = "from";
    public static final String FROM_OPEN_SDK = "from_open_sdk";
    public static final String GUILD_AVATAR = "guild_avatar";
    public static final String GUILD_ID = "guild_id";
    public static final String GUILD_NAME = "guild_name";
    public static final String GUILD_OPENID = "guild_openid";
    public static final String HTTP_GET = "GET";
    public static final String HTTP_POST = "POST";
    public static final int IM_AIO = 0;
    public static final int IM_AUDIO_CHAT = 1;
    public static final int IM_VIDEO_CHAT = 2;
    public static final String KEY_ACTION = "key_action";
    public static final String KEY_APP_NAME = "oauth_app_name";
    public static String KEY_ENABLE_SHOW_DOWNLOAD_URL = null;
    public static final String KEY_ERROR_CODE = "key_error_code";
    public static final String KEY_ERROR_DETAIL = "key_error_detail";
    public static final String KEY_ERROR_MSG = "key_error_msg";
    public static String KEY_GUILD_TYPE = null;
    public static String KEY_GUILD_URL = null;
    public static final String KEY_PARAMS = "key_params";
    public static String KEY_PASS_REPORT_VIA_PARAM = null;
    public static String KEY_PASS_REPORT_VIA_TIMELY = null;
    public static final String KEY_PPSTS = "ppsts";
    public static String KEY_PROXY_APPID = null;
    public static String KEY_QRCODE = null;
    public static final String KEY_REQUEST_CODE = "key_request_code";
    public static final String KEY_RESPONSE = "key_response";
    public static String KEY_RESTORE_LANDSCAPE = null;
    public static String KEY_SCOPE = null;
    public static final String KEY_STAY = "stay_back_stack";
    public static final String LOGIN_INFO = "login_info";
    public static final String MOBILEQQ_PACKAGE_NAME = "com.tencent.mobileqq";
    public static final String MSG_CONNECTTIMEOUT_ERROR = "\u7f51\u7edc\u8fde\u63a5\u8d85\u65f6!";
    public static final String MSG_IMAGE_ERROR = "\u56fe\u7247\u8bfb\u53d6\u5931\u8d25\uff0c\u8bf7\u68c0\u67e5\u8be5\u56fe\u7247\u662f\u5426\u6709\u6548";
    public static final String MSG_IO_ERROR = "\u7f51\u7edc\u8fde\u63a5\u5f02\u5e38\uff0c\u8bf7\u68c0\u67e5\u540e\u91cd\u8bd5!";
    public static final String MSG_JSON_ERROR = "\u670d\u52a1\u5668\u8fd4\u56de\u6570\u636e\u683c\u5f0f\u6709\u8bef!";
    public static final String MSG_LOCATION_TIMEOUT_ERROR = "\u5b9a\u4f4d\u8d85\u65f6\uff0c\u8bf7\u7a0d\u540e\u518d\u8bd5\u6216\u68c0\u67e5\u7f51\u7edc\u72b6\u51b5\uff01";
    public static final String MSG_LOCATION_VERIFY_ERROR = "\u5b9a\u4f4d\u5931\u8d25\uff0c\u9a8c\u8bc1\u5b9a\u4f4d\u7801\u9519\u8bef\uff01";
    public static final String MSG_LOGIN_NEEDED = "\u8bf7\u5148\u4f7f\u7528\u624bQ\u767b\u5f55";
    public static final String MSG_NOT_CALL_ON_MAIN_THREAD = "\u6ca1\u6709\u5728\u4e3b\u7ebf\u7a0b\u8c03\u7528\uff01";
    public static final String MSG_NO_SDCARD = "\u68c0\u6d4b\u4e0d\u5230SD\u5361\uff0c\u65e0\u6cd5\u53d1\u9001\u8bed\u97f3\uff01";
    public static final String MSG_OPEN_BROWSER_ERROR = "\u6253\u5f00\u6d4f\u89c8\u5668\u5931\u8d25!";
    public static final String MSG_PARAM_APPSHARE_TOO_LOW = "\u624bQ\u7248\u672c\u8fc7\u4f4e\uff0c\u5e94\u7528\u5206\u4eab\u53ea\u652f\u6301\u624bQ5.0\u53ca\u5176\u4ee5\u4e0a\u7248\u672c";
    public static final String MSG_PARAM_ERROR = "\u4f20\u5165\u53c2\u6570\u6709\u8bef!";
    public static final String MSG_PARAM_IMAGE_ERROR = "\u7eaf\u56fe\u5206\u4eab\uff0cimageUrl \u4e0d\u80fd\u4e3a\u7a7a";
    public static final String MSG_PARAM_IMAGE_URL_FORMAT_ERROR = "\u975e\u6cd5\u7684\u56fe\u7247\u5730\u5740!";
    public static final String MSG_PARAM_IMAGE_URL_MUST_BE_LOCAL = "\u624bQ\u7248\u672c\u8fc7\u4f4e\uff0c\u7eaf\u56fe\u5206\u4eab\u4e0d\u652f\u6301\u7f51\u8def\u56fe\u7247";
    public static final String MSG_PARAM_NULL_ERROR = "\u4f20\u5165\u53c2\u6570\u4e0d\u53ef\u4ee5\u4e3a\u7a7a";
    public static final String MSG_PARAM_QQ_VERSION_ERROR = "\u4f4e\u7248\u672c\u624bQ\u4e0d\u652f\u6301\u8be5\u9879\u529f\u80fd!";
    public static final String MSG_PARAM_TARGETURL_ERROR = "targetUrl\u6709\u8bef";
    public static final String MSG_PARAM_TARGETURL_NULL_ERROR = "targetUrl\u4e3a\u5fc5\u586b\u9879\uff0c\u8bf7\u8865\u5145\u540e\u5206\u4eab";
    public static final String MSG_PARAM_TITLE_NULL_ERROR = "title\u4e0d\u80fd\u4e3a\u7a7a!";
    public static final String MSG_PARAM_VERSION_TOO_LOW = "\u624bQ\u7248\u672c\u8fc7\u4f4e\uff0c\u8bf7\u4e0b\u8f7d\u5b89\u88c5\u6700\u65b0\u7248\u624bQ";
    public static final String MSG_PERMISSION_NOT_GRANTED = "\u7528\u6237\u672a\u6388\u6743\uff0c\u6682\u65f6\u65e0\u6cd5\u4f7f\u7528QQ\u767b\u5f55\u53ca\u5206\u4eab\u7b49\u529f\u80fd";
    public static final String MSG_PERSISTENCE_FAIL = "\u6301\u4e45\u5316\u5931\u8d25!";
    public static final String MSG_PROXY_LOGIN_QQ_VERSION_LOWER = "\u624bQ\u7248\u672c\u592a\u4f4e\uff0c\u4e0d\u652f\u6301\u59d4\u6258\u767b\u5f55!";
    public static final String MSG_PUBLISH_VIDEO_ERROR = "\u8bf7\u9009\u62e9\u6709\u6548\u7684\u89c6\u9891\u6587\u4ef6";
    public static final String MSG_SHARE_GETIMG_ERROR = "\u83b7\u53d6\u5206\u4eab\u56fe\u7247\u5931\u8d25!";
    public static final String MSG_SHARE_IMAGE_TOO_LARGE_ERROR = "\u56fe\u7247\u592a\u5927\uff0c\u8bf7\u538b\u7f29\u52305M\u5185\u518d\u5206\u4eab!";
    public static final String MSG_SHARE_NOSD_ERROR = "\u5206\u4eab\u56fe\u7247\u5931\u8d25\uff0c\u68c0\u6d4b\u4e0d\u5230SD\u5361!";
    public static final String MSG_SHARE_TO_QQ_ERROR = "\u5206\u4eab\u7684\u624b\u673aQQ\u5931\u8d25!";
    public static final String MSG_SHARE_TYPE_ERROR = "\u8bf7\u9009\u62e9\u652f\u6301\u7684\u5206\u4eab\u7c7b\u578b";
    public static final String MSG_SOCKETTIMEOUT_ERROR = "\u7f51\u7edc\u8fde\u63a5\u8d85\u65f6!";
    public static final String MSG_UNKNOWN_ERROR = "\u672a\u77e5\u9519\u8bef!";
    public static final String MSG_URL_ERROR = "\u8bbf\u95eeurl\u6709\u8bef!";
    public static final String NONCE = "nonce";
    public static final String OPENID = "openid";
    public static final String PACKAGE_ID = "package_id";
    public static final String PACKAGE_QIM = "com.tencent.qim";
    public static final String PACKAGE_QQ = "com.tencent.mobileqq";
    public static final String PACKAGE_QQ_PAD = "com.tencent.minihd.qq";
    public static final String PACKAGE_QQ_SPEED = "com.tencent.qqlite";
    public static final String PACKAGE_QZONE = "com.qzone";
    public static final String PACKAGE_TIM = "com.tencent.tim";
    public static final String PARAM_ACCESS_TOKEN = "access_token";
    public static final String PARAM_APP_ID = "appid";
    public static final String PARAM_APP_NAME = "app_name";
    public static final String PARAM_APP_VER = "app_ver";
    public static final String PARAM_AVATAR_URI = "picture";
    public static final String PARAM_CLIENT_ID = "client_id";
    public static final String PARAM_CONSUMER_KEY = "oauth_consumer_key";
    public static final String PARAM_EXPIRES_IN = "expires_in";
    public static final String PARAM_EXPIRES_TIME = "expires_time";
    public static final String PARAM_EXT_DATA = "opensdk_ext_data";
    public static final String PARAM_HOPEN_ID = "hopenid";
    public static final String PARAM_KEY_STR = "keystr";
    public static final String PARAM_KEY_TYPE = "keytype";
    public static final String PARAM_MODEL_NAME = "model_name";
    public static final String PARAM_OPEN_ID = "openid";
    public static final String PARAM_PKG_NAME = "pkg_name";
    public static final String PARAM_PLATFORM = "platform";
    public static final String PARAM_PLATFORM_ID = "pf";
    public static final String PARAM_QQ_VER = "qq_ver";
    public static final String PARAM_SCOPE = "scope";
    public static final String PARAM_SDK_VER = "sdk_ver";
    public static final String PARAM_SRC_ID = "src_id";
    public static final String PLATID = "platid";
    public static final String PREFERENCE_PF = "pfStore";
    public static final String QQ_APPID = "100686848";
    public static String QQ_SHARE_TEMP_DIR = null;
    public static final int REQUEST_API = 10100;
    public static final int REQUEST_APPBAR = 10102;
    public static final int REQUEST_AVATER = 11102;
    public static final int REQUEST_BIND_GROUP = 10112;
    public static final int REQUEST_COMMON_CHANNEL = 10114;
    public static final int REQUEST_EDIT_AVATAR = 10108;
    public static final int REQUEST_EDIT_DYNAMIC_AVATAR = 10110;
    public static final int REQUEST_EDIT_EMOTION = 10109;
    public static final int REQUEST_GUILD = 10113;
    public static final int REQUEST_JOIN_GROUP = 10111;
    public static final int REQUEST_LOGIN = 11101;
    public static final int REQUEST_OLD_QZSHARE = 11104;
    public static final int REQUEST_OLD_SHARE = 11103;
    public static final int REQUEST_QQ_FAVORITES = 10105;
    public static final int REQUEST_QQ_SHARE = 10103;
    public static final int REQUEST_QZONE_SHARE = 10104;
    public static final int REQUEST_SEND_TO_MY_COMPUTER = 10106;
    public static final int REQUEST_SHARE_TO_TROOP_BAR = 10107;
    public static final int REQUEST_SOCIAL_API = 11105;
    public static final int REQUEST_SOCIAL_H5 = 11106;
    public static final String SDK_QUA = "V1_AND_OpenSDK_3.5.13.lite_1077_RDM_B";
    public static final String SDK_VERSION = "3.5.13.lite";
    public static final String SDK_VERSION_REPORT = "OpenSdk_3.5.13.lite";
    public static final String SHARE_QQ_AND_STAY = "com.tencent.tauth.opensdk.SHARE_SUCCESS_AND_STAY_QQ_";
    public static final String SIGNATRUE_QZONE = "ec96e9ac1149251acbb1b0c5777cae95";
    public static final String SOURCE_QQ = "QQ";
    public static final String SOURCE_QZONE = "qzone";
    public static final String SPECIFY_UIN = "specify_uin";
    public static final String STR_EMPTY = "";
    public static final String TS = "ts";
    public static final int UI_ACTIVITY = 1;
    public static final int UI_CHECK_TOKEN = 3;
    public static final int UI_DIALOG = 2;
    public static final int UI_DOWNLOAD_QQ = 4;
    public static final int UI_NONE = -1;
    public static final int UI_PROXY_LOGIN_AND_NO_QQ = 5;
    public static String VALUE_GUILD_CREATE = null;
    public static String VALUE_GUILD_JOIN = null;
    public static final String VIA_ACT_TYPE_EIGHTEEN = "18";
    public static final String VIA_ACT_TYPE_FIVE = "5";
    public static final String VIA_ACT_TYPE_NINETEEN = "19";
    public static final String VIA_ACT_TYPE_SEVEN = "7";
    public static final String VIA_ACT_TYPE_THREE = "3";
    public static final String VIA_ACT_TYPE_TWENTY_EIGHT = "28";
    public static final String VIA_BIND_GROUP = "ANDROIDSDK.BINDGROUP.XX";
    public static final String VIA_CALL_SOURCE_H5 = "2";
    public static final String VIA_CALL_SOURCE_SQ = "1";
    public static final String VIA_JOIN_GROUP = "ANDROIDQQ.JOININGROUP.XX";
    public static final String VIA_MAKE_FRIEND = "ANDROIDQQ.MAKEAFRIEND.XX";
    public static final String VIA_NO_VALUE = "0";
    public static final String VIA_REPORT_TYPE_BIND_GROUP = "18";
    public static final String VIA_REPORT_TYPE_CHAT_AIO = "24";
    public static final String VIA_REPORT_TYPE_CHAT_AUDIO = "25";
    public static final String VIA_REPORT_TYPE_CHAT_VIDEO = "26";
    public static final String VIA_REPORT_TYPE_DATALINE = "22";
    public static final String VIA_REPORT_TYPE_JOININ_GROUP = "13";
    public static final String VIA_REPORT_TYPE_MAKE_FRIEND = "14";
    public static final String VIA_REPORT_TYPE_QQFAVORITES = "21";
    public static final String VIA_REPORT_TYPE_SET_AVATAR = "12";
    public static final String VIA_REPORT_TYPE_SHARE_TO_QQ = "10";
    public static final String VIA_REPORT_TYPE_SHARE_TO_QZONE = "11";
    public static final String VIA_REPORT_TYPE_SHARE_TO_TROOPBAR = "23";
    public static final String VIA_REPORT_TYPE_SSO_LOGIN = "1";
    public static final String VIA_REPORT_TYPE_START_GROUP = "17";
    public static final String VIA_REPORT_TYPE_START_WAP = "16";
    public static final String VIA_REPORT_TYPE_WPA_STATE = "15";
    public static final String VIA_RESULT_FAIL = "1";
    public static final String VIA_RESULT_SUCCESS = "0";
    public static final String VIA_SDK = "2";
    public static final String VIA_SET_AVATAR = "ANDROIDSDK.SETAVATAR.XX";
    public static final String VIA_SET_AVATAR_SUCCEED = "ANDROIDSDK.SETAVATAR.SUCCEED";
    public static final String VIA_SHARE_TO_QQ = "ANDROIDQQ.SHARETOQQ.XX";
    public static final String VIA_SHARE_TO_QZONE = "ANDROIDQQ.SHARETOQZ.XX";
    public static final String VIA_SHARE_TO_TROOPBAR = "ANDROIDSDK.SHARETOTROOPBAR.XX";
    public static final String VIA_SHARE_TYPE_IMAGE = "2";
    public static final String VIA_SHARE_TYPE_IMAGE_TEXT = "1";
    public static final String VIA_SHARE_TYPE_INFO = "6";
    public static final String VIA_SHARE_TYPE_MINI_PROGRAM = "9";
    public static final String VIA_SHARE_TYPE_MUSIC = "3";
    public static final String VIA_SHARE_TYPE_PUBLISHMOOD = "7";
    public static final String VIA_SHARE_TYPE_PUBLISHVIDEO = "8";
    public static final String VIA_SHARE_TYPE_TEXT = "5";
    public static final String VIA_SSO_LOGIN = "2";
    public static final String VIA_START_IM = "ANDROIDSDK.STARTIM.XX";
    public static final String VIA_START_WAP = "ANDROIDSDK.STARTWPA.XX";
    public static final String VIA_TO_TYPE_QQ_DISCUSS_GROUP = "3";
    public static final String VIA_TO_TYPE_QQ_FRIEND = "1";
    public static final String VIA_TO_TYPE_QQ_GROUP = "1";
    public static final String VIA_TO_TYPE_QZONE = "4";
    public static final String VIA_WAP_STATE = "ANDROIDSDK.WPASTATE.XX";
    public static final String ZONE_ID = "zone_id";

    /* JADX WARN: Classes with same name are omitted:
  E:\TSN-r\205dec\6206960.dex
 */
    /* compiled from: ProGuard */
    /* loaded from: E:\TSN-r\205dec\6400276.dex */
    public static class JumpUrlConstants {
        public static final int MAX_APP_NAME_LENGTH = 20;
        public static final String SRC_TYPE_APP = "app";
        public static final String URL_KEY_APPID = "app_id";
        public static final String URL_KEY_APP_NAME = "app_name";
        public static final String URL_KEY_OPENID = "open_id";
        public static final String URL_KEY_SDK_VERSION = "sdk_version";
        public static final String URL_KEY_SRC = "src_type";
    }

    static {
        StringBuilder sb = new StringBuilder();
        sb.append("tencent");
        String str = File.separator;
        sb.append(str);
        sb.append("mobileqq");
        sb.append(str);
        sb.append("opensdk");
        APP_SPECIFIC_ROOT = sb.toString();
        QQ_SHARE_TEMP_DIR = "tmp";
        KEY_RESTORE_LANDSCAPE = "key_restore_landscape";
        KEY_SCOPE = "key_scope";
        KEY_QRCODE = "key_qrcode";
        KEY_ENABLE_SHOW_DOWNLOAD_URL = "key_enable_show_download_url";
        KEY_PROXY_APPID = "key_proxy_appid";
        KEY_PASS_REPORT_VIA_PARAM = "key_pass_report_via_param";
        KEY_PASS_REPORT_VIA_TIMELY = "key_pass_report_via_timely";
        KEY_GUILD_TYPE = "guild_type";
        KEY_GUILD_URL = "guild_url";
        VALUE_GUILD_CREATE = "create";
        VALUE_GUILD_JOIN = "join";
    }
}
